## Contexto del juego

Los partidos de pádel registrados en este dataset corresponden a una variante recreativa
jugada por estudiantes universitarios. Las reglas de puntuación son las siguientes:

- El partido se juega en un formato de puntos directos (sin games ni sets).
- Gana el primer equipo en alcanzar **7 puntos** con una diferencia mínima de **2 puntos**.
- Si al llegar a 7 puntos no hay diferencia de 2, el partido continúa hasta
  que algún equipo la consiga.
- Cada punto es disputado por dos equipos de dos jugadores cada uno.
- Las posiciones de los jugadores en la cancha (LEFT/RIGHT, TOP/BOTTOM)
  pueden variar entre puntos dentro del mismo partido.

## EDA

**Base de Videos** (`Base_Videos_Final_202502.csv` / `Base_Videos_Final_202601.csv`)

| Variable | Tipo | Descripción |
|---|---|---|
| `frame_idx` | entero | Índice del frame dentro del video del punto |
| `duration` | decimal | Duración de cada frame en segundos (~0.0167 s = 60 fps) |
| `total_frames` | entero | Total de frames en el video del punto |
| `video_duration` | decimal | Duración total del video del punto en segundos |
| `player_id` | entero | Identificador numérico del jugador en el partido (1–4) |
| `player_name` | texto | Nombre completo del jugador |
| `team` | texto | Posición del equipo (top or bottom) |
| `zone` | texto | Zona de la cancha donde se ubica el jugador: *back_court*, *front_court*, etc. |
| `ball_position_x` | decimal | Posición horizontal de la pelota en la cancha (metros) |
| `ball_position_y` | decimal | Posición vertical de la pelota en la cancha (metros) |
| `player_position_x` | decimal | Posición horizontal del jugador en la cancha (metros) |
| `player_position_y` | decimal | Posición vertical del jugador en la cancha (metros) |
| `distance_ball_to_net` | decimal | Distancia de la pelota a la red (metros) |
| `distance_player_to_ball_m` | decimal | Distancia del jugador a la pelota (metros) |
| `distance_player_to_net_m` | decimal | Distancia del jugador a la red (metros) |
| `distance_player_to_teammate_m` | decimal | Distancia del jugador a su compañero de equipo (metros) |
| `player_hits_ball` | booleano | Si el jugador golpea la pelota en ese frame ('True'/'False' como texto) |
| `prev_x` | decimal | Posición X del jugador en el frame anterior (metros) |
| `prev_y` | decimal | Posición Y del jugador en el frame anterior (metros) |
| `player_displacement` | decimal | Desplazamiento del jugador respecto al frame anterior (metros) |
| `player_speed_mps` | decimal | Velocidad actual del jugador (metros/segundo) |
| `prev_speed` | decimal | Velocidad del jugador en el frame anterior (metros/segundo) |
| `player_acceleration_mps2` | decimal | Aceleración del jugador (metros/segundo²) |
| `ball_position_x_prev` | decimal | Posición X de la pelota en el frame anterior (metros) |
| `ball_position_y_prev` | decimal | Posición Y de la pelota en el frame anterior (metros) |
| `ball_displacement` | decimal | Desplazamiento de la pelota respecto al frame anterior (metros) |
| `ball_speed_mps` | decimal | Velocidad de la pelota (metros/segundo) |
| `time_since_last_hit` | decimal | Tiempo transcurrido desde el último golpe del jugador (segundos) |
| `partido` | entero | Identificador del partido al que pertenece el frame |
| `punto` | entero | Identificador del punto dentro del partido |

---

**Traza de Datos de Partidos** (`Traza_Datos_Partidos_202502.xlsx` / `_202601.xlsx` · 2 hojas: Cancha 1 y Cancha 2)

| Variable | Tipo | Descripción |
|---|---|---|
| `ID_PARTIDO` | entero | Identificador único del partido |
| `CANCHA` | entero | Número de la cancha donde se jugó (1 o 2) |
| `ID_PUNTO` | entero | Número de secuencia del punto dentro del partido |
| `ID_JUGADOR_1_EQUIPO_1` | texto | Nombre del jugador 1 del equipo 1 |
| `ID_JUGADOR_2_EQUIPO_1` | texto | Nombre del jugador 2 del equipo 1 |
| `ID_JUGADOR_1_EQUIPO_2` | texto | Nombre del jugador 1 del equipo 2 |
| `ID_JUGADOR_2_EQUIPO_2` | texto | Nombre del jugador 2 del equipo 2 |
| `EQUIPO_1_POSICION` | texto | Posición general del equipo 1 en la cancha: *BOTTOM* o *TOP* |
| `EQUIPO_2_POSICION` | texto | Posición general del equipo 2 en la cancha: *BOTTOM* o *TOP* |
| `POSICION_JUGADOR_1_EQUIPO_1` | texto | Lado de la cancha del jugador 1 equipo 1: *LEFT* o *RIGHT* |
| `POSICION_JUGADOR_2_EQUIPO_1` | texto | Lado de la cancha del jugador 2 equipo 1: *LEFT* o *RIGHT* |
| `POSICION_JUGADOR_1_EQUIPO_2` | texto | Lado de la cancha del jugador 1 equipo 2: *LEFT* o *RIGHT* |
| `POSICION_JUGADOR_2_EQUIPO_2` | texto | Lado de la cancha del jugador 2 equipo 2: *LEFT* o *RIGHT* |
| `PUNTO_EQUIPO_1` | entero | Si el equipo 1 ganó el punto (1 = ganó, 0 = perdió) |
| `PUNTO_EQUIPO_2` | entero | Si el equipo 2 ganó el punto (1 = ganó, 0 = perdió) |

---

**Datos de Jugadores** (`Datos_Jugadores_Padel_202502.xlsx` / `Data_Jugadores_202601.xlsx`)

| Variable | Tipo | Descripción |
|---|---|---|
| `Marca temporal` | fecha | Fecha y hora en que se diligenció el formulario |
| `NOMBRE` | texto | Nombre completo del jugador (clave de enlace con la traza de partidos) |
| `CODIGO_ESTUDIANTE` | texto | Código institucional del estudiante |
| `CIUDAD` | texto | Ciudad de residencia del jugador |
| `EDAD` | entero | Edad del jugador en años |
| `GENERO` | texto | Género del jugador |
| `PROGRAMA_ACADEMICO` | texto | Programa universitario que cursa |
| `SEMESTRE` | entero | Semestre académico actual |
| `EXPERIENCIA_PADEL` | texto | Si tiene experiencia previa en pádel (Sí/No) |
| `TIEMPO_JUGANDO_PADEL` | texto | Tiempo aproximado que lleva practicando pádel |
| `PRACTICA_OTRO_DEPORTE_RAQUETA` | texto | Si practica otro deporte de raqueta (tenis, squash, etc.) |
| `NIVEL_ACTUAL_PADEL` | texto | Nivel de juego autorreportado (principiante, intermedio, avanzado) |
| `ESTADO_FISICO` | texto | Percepción del jugador sobre su condición física actual |
| `FRECUENCIA_DEPORTE` | texto | Frecuencia semanal con la que practica deporte en general |
| `ESTATURA` | decimal | Estatura del jugador (verificar unidades: metros o centímetros) |
| `TALLA` | texto | Talla de ropa del jugador (S, M, L, XL, etc.) |
| `MANO_DOMINANTE` | texto | Mano dominante: derecha o izquierda |
| `RITMO_CARDIACO` | entero | Frecuencia cardíaca en reposo (ppm) |
| `LESIONES_LY` | texto | Si tuvo lesiones en el último año |
| `RAZON_PARTICIPACION` | texto | Motivo por el que participa en la actividad |
| `OBJETIVO_ACTIVIDAD` | texto | Objetivo personal con la actividad deportiva |
| `INTERES_PADEL` | texto | Nivel de interés en el pádel como deporte |
| `CLASES_PADEL` | texto | Si ha tomado clases formales de pádel |
| `DESAYUNO` | texto | Si desayunó el día de la actividad (Sí/No) |
| `¿Que desayunaste?` | texto | Descripción abierta de lo que desayunó |
| `GENERO_MUSICAL_FAVORITO` | texto | Género musical favorito (dato contextual) |
| `COMENTARIOS` | texto | Observaciones adicionales en texto libre |
| `Puntos_Ganados` | entero | Total de puntos ganados en todos sus partidos |
| `Puntos_Jugados` | entero | Total de puntos disputados |
| `Win_Rate` | decimal | Tasa de éxito: Puntos_Ganados / Puntos_Jugados (0 a 1) |

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import unicodedata
warnings.filterwarnings("ignore")

# Cargar el dataset
data_videos = pd.read_csv("./databases/2026-1/Base_Videos_Final_202601.csv")
data_partidos = pd.concat([
    pd.read_excel("./databases/2026-1/Traza_Datos_Partidos_202601.xlsx", sheet_name="CANCHA_1"),
    pd.read_excel("./databases/2026-1/Traza_Datos_Partidos_202601.xlsx", sheet_name="CANCHA_2")
], ignore_index=True)

In [50]:
def normalizar_nombre(nombre):
    if pd.isna(nombre):
        return nombre
    # Minúsculas, strip, title
    nombre = str(nombre).strip().lower().title()
    # Quitar tildes
    nombre = unicodedata.normalize('NFKD', nombre).encode('ascii', 'ignore').decode('utf-8')
    return nombre

# Normalizar en data_videos
data_videos['player_name'] = data_videos['player_name'].apply(normalizar_nombre)

# Normalizar en data_partidos
cols_jugadores = [
    'ID_JUGADOR_1_EQUIPO_1', 'ID_JUGADOR_2_EQUIPO_1',
    'ID_JUGADOR_1_EQUIPO_2', 'ID_JUGADOR_2_EQUIPO_2'
]
for col in cols_jugadores:
    data_partidos[col] = data_partidos[col].apply(normalizar_nombre)

In [51]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 1000)

### LIMPIEZA DE LOS DATOS

#### data_videos

##### Valores nulos

**Detección**

In [52]:
data_videos.info()

<class 'pandas.DataFrame'>
RangeIndex: 434198 entries, 0 to 434197
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   frame_idx                      434198 non-null  int64
 1   duration                       434198 non-null  float64
 2   total_frames                   434198 non-null  int64
 3   video_duration                 434198 non-null  float64
 4   player_id                      434198 non-null  int64
 5   player_name                    434198 non-null  str
 6   team                           225038 non-null  str
 7   zone                           434198 non-null  str
 8   ball_position_x                434198 non-null  float64
 9   ball_position_y                434198 non-null  float64
 10  player_position_x              434198 non-null  float64
 11  player_position_y              434198 non-null  float64
 12  distance_ball_to_net           434198 non-null  float64
 13  distance_player_to_ball_m      434198 non-null  float64
 14  distance_player_to_net_m       434198 non-null  float64
 15  distance_player_to_teammate_m  364803 non-null  float64
 16  player_hits_ball               434198 non-null  bool
 17  prev_x                         433023 non-null  float64
 18  prev_y                         433023 non-null  float64
 19  player_displacement            433023 non-null  float64
 20  player_speed_mps               433023 non-null  float64
 21  prev_speed                     431896 non-null  float64
 22  player_acceleration_mps2       431896 non-null  float64
 23  ball_position_x_prev           268831 non-null  float64
 24  ball_position_y_prev           268831 non-null  float64
 25  ball_displacement              268831 non-null  float64
 26  ball_speed_mps                 268831 non-null  float64
 27  time_since_last_hit            35577 non-null   float64
 28  partido                        434198 non-null  int64
 29  punto                          434198 non-null  int64
dtypes: bool(1), float64(21), int64(5), str(3)
memory usage: 96.5 MB

**Hallazgos**

- Hay frames en los cuales el equipo no es detectado team (la posición del equipo top or bottom) -> Al no cambiar durante la duración del punto el partido, se reemplazara con la media de ese punto o partido
- Hay casos en los que la distancia al compañero del jugador esta calculada en solo uno de los dos miembros del equipo -> Revisar la existencia de esos casos y corregirlo; En caso de que no pero se tengan las posiciones de los dos jugadores calcularlo para amos
- Los valores nulos de las variables prev_x, prev_y, player_displacement, player_speed, prev_speed, player_acceleration, ball_position_x_prev, ball_position_y_prev, ball_displacement, ball_speed_mps, son nulos en los primeros frames de cada punto -> Se plantea eliminar las filas de estos primeros frames
- Los valores nulos de las variables ball_position_x_prev, ball_position_y_prev, ball_displacement, ball_speed_mps que no son el primer frame no son calculadas -> Revisar si se cuenta con las posiciones de la pelota y corregirlo
- time_since_last_hit es nulo si al principio de cada punto hasta que no se golpee por primera vez -> imputar con -1, indica que no ha sido golpeado todavia
- tras una primera limpieza de los primeros frames quedarón apenas 285 nulos en las variables de ball_position_x_prev, ball_position_y_prev, ball_displacement, ball_speed_mps -> al ser tan pocos se opto por su eliminación
- Ya que en el tratamiento data_videos, cuando la variable team era nula se quiero comprobar con la información data_partidos

**Tratamiento**

In [53]:
# ============================================================
# TRATAMIENTO DE VALORES NULOS - data_videos
# ============================================================

# ------------------------------------------------------------
# 1. Eliminar primeros frames de cada punto
# ------------------------------------------------------------
data_videos = data_videos[data_videos['frame_idx'] != 0].reset_index(drop=True)

# Eliminar nulos residuales en prev_speed y player_acceleration_mps2
# (frame 1 de cada punto, que necesitaba frame 0 como referencia)
data_videos = data_videos.dropna(
    subset=['prev_speed', 'player_acceleration_mps2']
).reset_index(drop=True)

# ------------------------------------------------------------
# 2. Imputar time_since_last_hit con -1
# ------------------------------------------------------------
data_videos['time_since_last_hit'] = data_videos['time_since_last_hit'].fillna(-1)

# ------------------------------------------------------------
# 3. Imputar team con la moda (punto -> partido -> jugador)
# ------------------------------------------------------------

# ============================================================
# ESTRATEGIA: usar data_partidos como fuente de verdad para team
# Reasignar team en data_videos según el nombre del jugador
# ============================================================

# 1. Construir lookup: partido → jugador → team correcto (de data_partidos)
lookup = pd.melt(
    data_partidos[[
        'ID_PARTIDO',
        'ID_JUGADOR_1_EQUIPO_1', 'ID_JUGADOR_2_EQUIPO_1',
        'ID_JUGADOR_1_EQUIPO_2', 'ID_JUGADOR_2_EQUIPO_2',
        'EQUIPO_1_POSICION', 'EQUIPO_2_POSICION'
    ]].drop_duplicates('ID_PARTIDO'),  # un registro por partido
    id_vars=['ID_PARTIDO', 'EQUIPO_1_POSICION', 'EQUIPO_2_POSICION'],
    value_vars=[
        'ID_JUGADOR_1_EQUIPO_1', 'ID_JUGADOR_2_EQUIPO_1',
        'ID_JUGADOR_1_EQUIPO_2', 'ID_JUGADOR_2_EQUIPO_2'
    ],
    var_name='rol',
    value_name='player_name'
)

lookup['team_correcto'] = lookup.apply(
    lambda r: r['EQUIPO_1_POSICION'] if 'EQUIPO_1' in r['rol'] else r['EQUIPO_2_POSICION'],
    axis=1
).str.upper()

lookup = lookup.rename(columns={'ID_PARTIDO': 'partido'})[
    ['partido', 'player_name', 'team_correcto']
]

# 2. Merge con data_videos
data_videos = data_videos.merge(lookup, on=['partido', 'player_name'], how='left')

# 3. Reemplazar team solo donde hay match (Player_X quedan con el team original)
mask_con_match = data_videos['team_correcto'].notna()
data_videos.loc[mask_con_match, 'team'] = data_videos.loc[mask_con_match, 'team_correcto']

data_videos = data_videos.drop(columns='team_correcto')

# 4. Diagnóstico
total = len(data_videos)
corregidos = mask_con_match.sum()
sin_match  = (~mask_con_match).sum()
print(f"Total frames:          {total:,}")
print(f"Team corregido:        {corregidos:,} ({corregidos/total*100:.1f}%)")
print(f"Sin match (Player_X):  {sin_match:,} ({sin_match/total*100:.1f}%)")

# ------------------------------------------------------------
# 4. Imputar distance_player_to_teammate_m (sin merge)
# ------------------------------------------------------------
data_videos = data_videos.sort_values(
    ['partido', 'punto', 'frame_idx', 'team', 'player_id']
).reset_index(drop=True)

# Dentro de cada frame y equipo, el compañero es el otro jugador
# shift(1) y shift(-1) dan la posición del otro miembro del equipo
grp_equipo = data_videos.groupby(['partido', 'punto', 'frame_idx', 'team'])

companero_x = grp_equipo['player_position_x'].transform(
    lambda g: g.iloc[::-1].values  # invierte el par [j1, j2] -> [j2, j1]
)
companero_y = grp_equipo['player_position_y'].transform(
    lambda g: g.iloc[::-1].values
)

distancia_calculada = np.sqrt(
    (data_videos['player_position_x'] - companero_x)**2 +
    (data_videos['player_position_y'] - companero_y)**2
)

data_videos['distance_player_to_teammate_m'] = data_videos[
    'distance_player_to_teammate_m'
].fillna(distancia_calculada)

print("Shape después del paso 4:", data_videos.shape)

# ------------------------------------------------------------
# 5. Recalcular variables de pelota donde sean nulas
# ------------------------------------------------------------
data_videos = data_videos.sort_values(
    ['partido', 'punto', 'player_id', 'frame_idx']
).reset_index(drop=True)

grp = data_videos.groupby(['partido', 'punto', 'player_id'])

data_videos['ball_position_x_prev'] = data_videos['ball_position_x_prev'].fillna(
    grp['ball_position_x'].shift(1)
)
data_videos['ball_position_y_prev'] = data_videos['ball_position_y_prev'].fillna(
    grp['ball_position_y'].shift(1)
)

ball_disp_calculado = np.sqrt(
    (data_videos['ball_position_x'] - data_videos['ball_position_x_prev'])**2 +
    (data_videos['ball_position_y'] - data_videos['ball_position_y_prev'])**2
)
data_videos['ball_displacement'] = data_videos['ball_displacement'].fillna(
    ball_disp_calculado
)

data_videos['ball_speed_mps'] = data_videos['ball_speed_mps'].fillna(
    data_videos['ball_displacement'] / data_videos['duration']
)

# Eliminar nulos residuales de variables de pelota (0.08% de los datos)
data_videos = data_videos.dropna(subset=[
    'ball_position_x_prev',
    'ball_position_y_prev',
    'ball_displacement',
    'ball_speed_mps'
]).reset_index(drop=True)

# ------------------------------------------------------------
# Verificación final
# ------------------------------------------------------------
nulos = data_videos.isnull().sum()
nulos_restantes = nulos[nulos > 0]

if nulos_restantes.empty:
    print("\nSin nulos restantes")
else:
    print("\nNulos restantes por columna:")
    print(nulos_restantes)

print(f"\nShape final: {data_videos.shape}")

Total frames:          431,896
Team corregido:        417,207 (96.6%)
Sin match (Player_X):  14,689 (3.4%)
Shape después del paso 4: (431896, 30)

Nulos restantes por columna:
team                             6505
distance_player_to_teammate_m    1533
dtype: int64

Shape final: (431596, 30)

##### Outliers

**Detección**

Para el detección de los outliers se realizó una comparación utilizando el rango inerquartilico y unos límitos físicos previamente definidos, esto debido a que varias variables como player_speed_mps, player_acceleration_mps2, ball_speed_mps, ball_displacement y player_displacement en su mayoría de valores son iguales a cero afectando su capacidad para definir unos límites inferiores y superiore fiables, como se puede ver a continuación:

In [54]:
# ============================================================
# DETECCIÓN DE OUTLIERS - Comparación IQR vs Límites Físicos
# ============================================================

vars_numericas = [
    'player_speed_mps', 'player_acceleration_mps2',
    'ball_speed_mps', 'ball_displacement',
    'distance_player_to_ball_m', 'distance_player_to_net_m',
    'distance_player_to_teammate_m', 'player_displacement'
]

limites_fisicos = {
    'player_speed_mps':              (0, 7),
    'player_acceleration_mps2':      (-10, 10),
    'ball_speed_mps':                (0, 50),
    'ball_displacement':             (0, 20),
    'distance_player_to_ball_m':     (0, 20),
    'distance_player_to_net_m':      (0, 10),
    'distance_player_to_teammate_m': (0, 10),
    'player_displacement':           (0, 2),
}

resultados = []

for col in vars_numericas:
    # --- IQR (3x) ---
    Q1 = data_videos[col].quantile(0.25)
    Q3 = data_videos[col].quantile(0.75)
    IQR = Q3 - Q1
    lim_iqr_inf = Q1 - 3 * IQR
    lim_iqr_sup = Q3 + 3 * IQR
    mask_iqr = (data_videos[col] < lim_iqr_inf) | (data_videos[col] > lim_iqr_sup)
    n_iqr = mask_iqr.sum()

    # --- Límites físicos ---
    min_fis, max_fis = limites_fisicos[col]
    mask_fis = (data_videos[col] < min_fis) | (data_videos[col] > max_fis)
    n_fis = mask_fis.sum()

    # --- Solo IQR / Solo físico / Ambos ---
    solo_iqr  = (mask_iqr & ~mask_fis).sum()
    solo_fis  = (mask_fis & ~mask_iqr).sum()
    ambos     = (mask_iqr & mask_fis).sum()

    resultados.append({
        'variable':          col,
        'min_real':          data_videos[col].min(),
        'max_real':          data_videos[col].max(),
        'lim_iqr_inf':       lim_iqr_inf,
        'lim_iqr_sup':       lim_iqr_sup,
        'lim_fis_inf':       min_fis,
        'lim_fis_sup':       max_fis,
        'outliers_iqr':      n_iqr,
        'outliers_iqr_%':    round(n_iqr / len(data_videos) * 100, 3),
        'outliers_fis':      n_fis,
        'outliers_fis_%':    round(n_fis / len(data_videos) * 100, 3),
        'solo_iqr':          solo_iqr,
        'solo_fisico':       solo_fis,
        'ambos':             ambos,
    })

df_comparacion = pd.DataFrame(resultados).set_index('variable')

pd.set_option('display.float_format', '{:.3f}'.format)
print("=== Comparación IQR vs Límites Físicos ===\n")
print(df_comparacion.to_string())

=== Comparación IQR vs Límites Físicos ===

                                min_real  max_real  lim_iqr_inf  lim_iqr_sup  lim_fis_inf  lim_fis_sup  outliers_iqr  outliers_iqr_%  outliers_fis  outliers_fis_%  solo_iqr  solo_fisico   ambos
variable
player_speed_mps                   0.000   562.860        0.000        0.000            0            7         75872          17.579          5260           1.219     70612            0    5260
player_acceleration_mps2      -33534.611 33534.611        0.000        0.000          -10           10        120454          27.909        117327          27.184      3127            0  117327
ball_speed_mps                     0.000   976.108        0.000        0.000            0           50         83472          19.340          2906           0.673     80566            0    2906
ball_displacement                  0.000    16.285        0.000        0.000            0           20         83472          19.340             0           0.000     83472            0       0
distance_player_to_ball_m          0.040    24.599      -14.022       29.070            0           20             0           0.000           799           0.185         0          799       0
distance_player_to_net_m           0.000    15.467       -0.889       13.733            0           10           487           0.113          6106           1.415         0         5619     487
distance_player_to_teammate_m      0.000    19.787       -2.559       11.556            0           10         39916           9.248         51829          12.009         0        11913   39916
player_displacement                0.000     9.390        0.000        0.000            0            2         75872          17.579          1919           0.445     73953            0    1919

**Hallazgos**

Como se comentó, en varias de estar variables, los limites que definió el rango interquartilico fueron cero o incluso valores negativos en el caso de las distancias.

**Tratamiento**

In [55]:
# ============================================================
# TRATAMIENTO DE OUTLIERS - Clipeo por límites físicos
# ============================================================

for col, (min_val, max_val) in limites_fisicos.items():
    if col == 'ball_displacement':
        continue  # sin outliers reales
    data_videos[col] = data_videos[col].clip(lower=min_val, upper=max_val)

# Verificación
print("=== Verificación post-clipeo ===")
for col, (min_val, max_val) in limites_fisicos.items():
    real_min = data_videos[col].min()
    real_max = data_videos[col].max()
    ok = "OK" if real_min >= min_val and real_max <= max_val else "REVISAR"
    print(f"{ok} | {col}: [{real_min:.3f}, {real_max:.3f}]")

=== Verificación post-clipeo ===
OK | player_speed_mps: [0.000, 7.000]
OK | player_acceleration_mps2: [-10.000, 10.000]
OK | ball_speed_mps: [0.000, 50.000]
OK | ball_displacement: [0.000, 16.285]
OK | distance_player_to_ball_m: [0.040, 20.000]
OK | distance_player_to_net_m: [0.000, 10.000]
OK | distance_player_to_teammate_m: [0.000, 10.000]
OK | player_displacement: [0.000, 2.000]

### data_partidos

#### Valores nulos

**Detección**

In [56]:
print(data_partidos.shape)
data_partidos.info()

(406, 15)
<class 'pandas.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID_PARTIDO                   406 non-null    int64
 1   CANCHA                       406 non-null    int64
 2   ID_PUNTO                     406 non-null    int64
 3   ID_JUGADOR_1_EQUIPO_1        406 non-null    str
 4   ID_JUGADOR_2_EQUIPO_1        406 non-null    str
 5   ID_JUGADOR_1_EQUIPO_2        406 non-null    str
 6   ID_JUGADOR_2_EQUIPO_2        406 non-null    str
 7   EQUIPO_1_POSICION            406 non-null    str
 8   EQUIPO_2_POSICION            406 non-null    str
 9   POSICION_JUGADOR_1_EQUIPO_1  406 non-null    str
 10  POSICION_JUGADOR_2_EQUIPO_1  406 non-null    str
 11  POSICION_JUGADOR_1_EQUIPO_2  406 non-null    str
 12  POSICION_JUGADOR_2_EQUIPO_2  406 non-null    str
 13  PUNTO_EQUIPO_1               406 non-null    int64
 14  PUNTO_EQUIPO_2               406 non-null    int64
dtypes: int64(5), str(10)
memory usage: 47.7 KB

In [57]:
data_partidos.sample(20)

,ID_PARTIDO,CANCHA,ID_PUNTO,ID_JUGADOR_1_EQUIPO_1,ID_JUGADOR_2_EQUIPO_1,ID_JUGADOR_1_EQUIPO_2,ID_JUGADOR_2_EQUIPO_2,EQUIPO_1_POSICION,EQUIPO_2_POSICION,POSICION_JUGADOR_1_EQUIPO_1,POSICION_JUGADOR_2_EQUIPO_1,POSICION_JUGADOR_1_EQUIPO_2,POSICION_JUGADOR_2_EQUIPO_2,PUNTO_EQUIPO_1,PUNTO_EQUIPO_2
329,26,2,11,Juan Esteban Bustos Marin,Yeison David Nino Arias,Jose Fabian Garcia,Luis Felipe Bonilla Patino,TOP,BOTTOM,LEFT,RIGHT,RIGHT,LEFT,0,1
89,17,1,8,Juan David Rubio,Sahily Andrea Herrera Eljadue,Isabella Buitrago,Pia Aroor,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,0,1
387,36,2,5,Laura Natalia Garcia,Cesar Camilo Diaz Cufino,Gabriel Alejandro Corzo Fernandez,Yeison David Nino Arias,TOP,BOTTOM,RIGHT,LEFT,LEFT,RIGHT,0,1
227,8,2,1,Juan Guio,Samuel Francisco Rubio Casallas,Sahily Andrea Herrera Eljadue,Daniel Esteban Ortegon Jaramillo,TOP,BOTTOM,RIGHT,LEFT,RIGHT,LEFT,1,0
231,8,2,1,Juan Guio,Samuel Francisco Rubio Casallas,Sahily Andrea Herrera Eljadue,Daniel Esteban Ortegon Jaramillo,TOP,BOTTOM,RIGHT,LEFT,RIGHT,LEFT,0,1
354,30,2,6,Juan Sebastian Melo Gonzalez,Juan David Quitian,Jorge Garcia,Juliana Gomez,TOP,BOTTOM,RIGHT,LEFT,RIGHT,LEFT,1,0
194,35,1,7,Juan David Rubio,Luis Felipe Bonilla Patino,Laura Natalia Garcia,Angel Santiago Toribio Godoy,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,1,0
264,4,2,8,Carlos Andres Diaz Mendez,Sofia Daza Garcia,Laura Natalia Garcia,Juan David Rubio,TOP,BOTTOM,LEFT,RIGHT,LEFT,RIGHT,1,0
277,12,2,7,Luis Felipe Bonilla Patino,Esteban Sequeda Henao,Luis Felipe Cuellar Santamaria,Daniel Esteban Ortegon Jaramillo,TOP,BOTTOM,LEFT,RIGHT,RIGHT,LEFT,0,1
46,9,1,5,Daniel Esteban Ortegon Jaramillo,Gabriel Alejandro Corzo Fernandez,Esteban Sequeda Henao,Juan Felipe Mahecha,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,0,1
325,26,2,7,Juan Esteban Bustos Marin,Yeison David Nino Arias,Jose Fabian Garcia,Luis Felipe Bonilla Patino,TOP,BOTTOM,LEFT,RIGHT,RIGHT,LEFT,0,1
244,10,2,11,Jorge Garcia,Jeronimo Sanabria Olivares,Yeison David Nino Arias,Juan Guio,TOP,BOTTOM,RIGHT,LEFT,LEFT,RIGHT,0,1
27,5,1,6,Isabella Buitrago,Samuel Francisco Rubio Casallas,Mateo Ramirez Cabrera,Maria Jose Palomino Carreno,TOP,BOTTOM,LEFT,RIGHT,LEFT,RIGHT,0,1
204,2,2,5,Sergio Gomez Osorio,Yeison David Nino Arias,Juan Felipe Mahecha,Luis Felipe Cuellar Santamaria,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,0,1
272,12,2,3,Luis Felipe Bonilla Patino,Esteban Sequeda Henao,Luis Felipe Cuellar Santamaria,Daniel Esteban Ortegon Jaramillo,TOP,BOTTOM,LEFT,RIGHT,RIGHT,LEFT,0,1
249,14,2,3,Juliana Gomez,Juan Sebastian Melo Gonzalez,Santiago Pena Beltran,Juan David Quitian,TOP,BOTTOM,RIGHT,LEFT,LEFT,RIGHT,1,0
305,20,2,4,Carlos Felipe Andrade,Sofia Daza Garcia,Pia Aroor,Laura Natalia Garcia,TOP,BOTTOM,RIGHT,LEFT,RIGHT,LEFT,1,0
149,29,1,8,Juan Sebastian Melo Gonzalez,Alejandra Salazar Galeano,Sahily Andrea Herrera Eljadue,Samuel Francisco Rubio Casallas,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,0,1
241,10,2,8,Jorge Garcia,Jeronimo Sanabria Olivares,Yeison David Nino Arias,Juan Guio,TOP,BOTTOM,RIGHT,LEFT,LEFT,RIGHT,1,0
189,35,1,2,Juan David Rubio,Luis Felipe Bonilla Patino,Laura Natalia Garcia,Angel Santiago Toribio Godoy,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,0,1

**Hallazgos**

No se encontró ningún dato nulo

#### Outliers

**Detección**

Todas las variables de esta base de datos son indices y variables categoricas. Teniendo esto en cuenta, lo que quedaba por revisar era el formato y las categorias de estas variables.

**Hallazgos**

- No se encontrarón valores que sobresalieran de las categorías que se esperaban. 
- Sim embago, los nombres de algunos participantes tenian un formato diferente al de los demás (todo en mayúsculas), por lo cual se procede a formatear estas celdas.

**Tratamiento**

In [58]:
# ============================================================
# FORMATEO DE NOMBRES DE JUGADORES - data_partidos
# ============================================================

cols_jugadores = [
    'ID_JUGADOR_1_EQUIPO_1',
    'ID_JUGADOR_2_EQUIPO_1',
    'ID_JUGADOR_1_EQUIPO_2',
    'ID_JUGADOR_2_EQUIPO_2'
]

for col in cols_jugadores:
    data_partidos[col] = data_partidos[col].str.strip().str.title()

# Verificación
print("=== Muestra post-formateo ===")
print(data_partidos[cols_jugadores].drop_duplicates().to_string())

=== Muestra post-formateo ===
                 ID_JUGADOR_1_EQUIPO_1              ID_JUGADOR_2_EQUIPO_1              ID_JUGADOR_1_EQUIPO_2              ID_JUGADOR_2_EQUIPO_2
0            Alejandra Salazar Galeano       Angel Santiago Toribio Godoy              Santiago Pena Beltran      Sahily Andrea Herrera Eljadue
11                    Juan David Rubio              Santiago Pena Beltran          Alejandra Salazar Galeano               Laura Natalia Garcia
22                   Isabella Buitrago    Samuel Francisco Rubio Casallas              Mateo Ramirez Cabrera        Maria Jose Palomino Carreno
33           Juan Esteban Bustos Marin                  Sofia Daza Garcia  Gabriel Alejandro Corzo Fernandez       Angel Santiago Toribio Godoy
42    Daniel Esteban Ortegon Jaramillo  Gabriel Alejandro Corzo Fernandez              Esteban Sequeda Henao                Juan Felipe Mahecha
51   Gabriel Alejandro Corzo Fernandez                          Pia Aroor           Cesar Camilo Diaz Cufino                  Isabella Buitrago
60               Santiago Pena Beltran          Carlos Andres Diaz Mendez                Andre Leonard Duque                 Juan David Quitian
71                        Jorge Garcia            Juan David Ortiz Rendon              Esteban Sequeda Henao           Cesar Camilo Diaz Cufino
82                    Juan David Rubio      Sahily Andrea Herrera Eljadue                  Isabella Buitrago                          Pia Aroor
91                       Juliana Gomez            Juan David Ortiz Rendon              Mateo Ramirez Cabrera                 Nicolas Navarro D.
101                      Natalia Perez                  Sofia Daza Garcia              Tiffany Cardona Perez    Samuel Francisco Rubio Casallas
111   Daniel Esteban Ortegon Jaramillo                Juan Felipe Mahecha              Tiffany Cardona Perez              Esteban Sequeda Henao
124           Cesar Camilo Diaz Cufino               Laura Natalia Garcia                Sergio Gomez Osorio       Juan Sebastian Melo Gonzalez
133   Daniel Esteban Ortegon Jaramillo              Mateo Ramirez Cabrera           Cesar Camilo Diaz Cufino                          Pia Aroor
142       Juan Sebastian Melo Gonzalez          Alejandra Salazar Galeano      Sahily Andrea Herrera Eljadue    Samuel Francisco Rubio Casallas
154                          Pia Aroor         Luis Felipe Bonilla Patino              Carlos Felipe Andrade               Laura Natalia Garcia
166   Daniel Esteban Ortegon Jaramillo                Juan Felipe Mahecha         Luis Felipe Bonilla Patino              Mateo Ramirez Cabrera
176                          Juan Guio              Mateo Ramirez Cabrera                 Juan David Quitian                 Nicolas Navarro D.
188                   Juan David Rubio         Luis Felipe Bonilla Patino               Laura Natalia Garcia       Angel Santiago Toribio Godoy
200                Sergio Gomez Osorio            Yeison David Nino Arias                Juan Felipe Mahecha     Luis Felipe Cuellar Santamaria
213              Carlos Felipe Andrade                 Juan David Quitian            Juan David Ortiz Rendon                          Juan Guio
224                          Juan Guio    Samuel Francisco Rubio Casallas      Sahily Andrea Herrera Eljadue   Daniel Esteban Ortegon Jaramillo
234                       Jorge Garcia         Jeronimo Sanabria Olivares            Yeison David Nino Arias                          Juan Guio
247                      Juliana Gomez       Juan Sebastian Melo Gonzalez              Santiago Pena Beltran                 Juan David Quitian
257          Carlos Andres Diaz Mendez                  Sofia Daza Garcia               Laura Natalia Garcia                   Juan David Rubio
270         Luis Felipe Bonilla Patino              Esteban Sequeda Henao     Luis Felipe Cuellar Santamaria   Daniel Esteban Ortegon Jaramillo
280         Luis Felipe Bonilla Patino                       Jorge Garcia                Juan Felipe Mahecha                  Isabella Buitrago
292                          Juan Guio            Yeison David Nino Arias                      Juliana Gomez         Luis Felipe Bonilla Patino
302              Carlos Felipe Andrade                  Sofia Daza Garcia                          Pia Aroor               Laura Natalia Garcia
309                 Nicolas Navarro D.          Juan Esteban Bustos Marin                Juan Felipe Mahecha              Carlos Felipe Andrade
319          Juan Esteban Bustos Marin            Yeison David Nino Arias                 Jose Fabian Garcia         Luis Felipe Bonilla Patino
331            Juan David Ortiz Rendon                Sergio Gomez Osorio              Mateo Ramirez Cabrera   Daniel Esteban Ortegon Jaramillo
341       Juan Sebastian Melo Gonzalez                Sergio Gomez Osorio                      Juliana Gomez  Gabriel Alejandro Corzo Fernandez
349       Juan Sebastian Melo Gonzalez                 Juan David Quitian                       Jorge Garcia                      Juliana Gomez
362                       Jorge Garcia                      Juliana Gomez                Sergio Gomez Osorio                          Juan Guio
375                      Juliana Gomez          Alejandra Salazar Galeano              Esteban Sequeda Henao                   Juan David Rubio
383               Laura Natalia Garcia           Cesar Camilo Diaz Cufino  Gabriel Alejandro Corzo Fernandez            Yeison David Nino Arias
396                 Jose Fabian Garcia          Juan Esteban Bustos Marin         Luis Felipe Bonilla Patino              Esteban Sequeda Henao

### Construcción de la variable objetivo y variables de contexto

> **Nota:** El partido con ID 23 finalizó con marcador 7-6 (diferencia de 1 punto),
> lo cual no cumple la regla de diferencia mínima. Se trata como un error de
> registro y no afecta el análisis.

In [59]:
# ============================================================
# CONSTRUCCIÓN DE LA VARIABLE OBJETIVO Y VARIABLES DE CONTEXTO
# ============================================================

data_partidos = data_partidos.sort_values(['ID_PARTIDO', 'ID_PUNTO']).reset_index(drop=True)

# ------------------------------------------------------------
# 1. Marcador acumulado (ya calculado, verificar que existe)
# ------------------------------------------------------------
data_partidos['MARCADOR_EQUIPO_1'] = (
    data_partidos.groupby('ID_PARTIDO')['PUNTO_EQUIPO_1'].cumsum()
)
data_partidos['MARCADOR_EQUIPO_2'] = (
    data_partidos.groupby('ID_PARTIDO')['PUNTO_EQUIPO_2'].cumsum()
)

# ------------------------------------------------------------
# 2. Ganador del partido (variable objetivo)
# ------------------------------------------------------------
ganador_partido = (
    data_partidos.groupby('ID_PARTIDO')
    .last()[['MARCADOR_EQUIPO_1', 'MARCADOR_EQUIPO_2']]
    .apply(lambda row: 1 if row['MARCADOR_EQUIPO_1'] > row['MARCADOR_EQUIPO_2'] else 2, axis=1)
    .rename('EQUIPO_GANADOR')
    .reset_index()
)

data_partidos = data_partidos.merge(ganador_partido, on='ID_PARTIDO')

# ------------------------------------------------------------
# 3. Variables de contexto del marcador
# ------------------------------------------------------------
data_partidos['DIFERENCIA_MARCADOR'] = (
    data_partidos['MARCADOR_EQUIPO_1'] - data_partidos['MARCADOR_EQUIPO_2']
)
data_partidos['PUNTOS_JUGADOS'] = (
    data_partidos['MARCADOR_EQUIPO_1'] + data_partidos['MARCADOR_EQUIPO_2']
)
data_partidos['WINRATE_ACUM_E1'] = (
    data_partidos['MARCADOR_EQUIPO_1'] / data_partidos['PUNTOS_JUGADOS']
)
data_partidos['WINRATE_ACUM_E2'] = (
    data_partidos['MARCADOR_EQUIPO_2'] / data_partidos['PUNTOS_JUGADOS']
)

# ------------------------------------------------------------
# 4. Variables de momentum
# ------------------------------------------------------------
# Racha de puntos consecutivos por equipo
def calcular_racha(serie):
    racha = []
    contador = 0
    for val in serie:
        if val == 1:
            contador += 1
        else:
            contador = 0
        racha.append(contador)
    return racha

data_partidos['RACHA_EQUIPO_1'] = (
    data_partidos.groupby('ID_PARTIDO')['PUNTO_EQUIPO_1']
    .transform(calcular_racha)
)
data_partidos['RACHA_EQUIPO_2'] = (
    data_partidos.groupby('ID_PARTIDO')['PUNTO_EQUIPO_2']
    .transform(calcular_racha)
)

# Puntos ganados en los últimos 5 puntos
data_partidos['PUNTOS_ULTIMOS_5_E1'] = (
    data_partidos.groupby('ID_PARTIDO')['PUNTO_EQUIPO_1']
    .transform(lambda x: x.rolling(5, min_periods=1).sum())
)
data_partidos['PUNTOS_ULTIMOS_5_E2'] = (
    data_partidos.groupby('ID_PARTIDO')['PUNTO_EQUIPO_2']
    .transform(lambda x: x.rolling(5, min_periods=1).sum())
)

# ------------------------------------------------------------
# Verificación
# ------------------------------------------------------------
print(data_partidos[[
    'ID_PARTIDO', 'ID_PUNTO',
    'MARCADOR_EQUIPO_1', 'MARCADOR_EQUIPO_2',
    'DIFERENCIA_MARCADOR', 'PUNTOS_JUGADOS',
    'RACHA_EQUIPO_1', 'RACHA_EQUIPO_2',
    'PUNTOS_ULTIMOS_5_E1', 'PUNTOS_ULTIMOS_5_E2',
    'WINRATE_ACUM_E1', 'WINRATE_ACUM_E2',
    'EQUIPO_GANADOR'
]].head(20).to_string())

    ID_PARTIDO  ID_PUNTO  MARCADOR_EQUIPO_1  MARCADOR_EQUIPO_2  DIFERENCIA_MARCADOR  PUNTOS_JUGADOS  RACHA_EQUIPO_1  RACHA_EQUIPO_2  PUNTOS_ULTIMOS_5_E1  PUNTOS_ULTIMOS_5_E2  WINRATE_ACUM_E1  WINRATE_ACUM_E2  EQUIPO_GANADOR
0            1         1                  1                  0                    1               1               1               0                1.000                0.000            1.000            0.000               1
1            1         2                  2                  0                    2               2               2               0                2.000                0.000            1.000            0.000               1
2            1         3                  2                  1                    1               3               0               1                2.000                1.000            0.667            0.333               1
3            1         4                  2                  2                    0               4               0               2                2.000                2.000            0.500            0.500               1
4            1         5                  2                  3                   -1               5               0               3                2.000                3.000            0.400            0.600               1
5            1         6                  3                  3                    0               6               1               0                2.000                3.000            0.500            0.500               1
6            1         7                  4                  3                    1               7               2               0                2.000                3.000            0.571            0.429               1
7            1         8                  5                  3                    2               8               3               0                3.000                2.000            0.625            0.375               1
8            1         9                  6                  3                    3               9               4               0                4.000                1.000            0.667            0.333               1
9            1        10                  6                  4                    2              10               0               1                4.000                1.000            0.600            0.400               1
10           1        11                  7                  4                    3              11               1               0                4.000                1.000            0.636            0.364               1
11           2         1                  1                  0                    1               1               1               0                1.000                0.000            1.000            0.000               2
12           2         2                  2                  0                    2               2               2               0                2.000                0.000            1.000            0.000               2
13           2         3                  2                  1                    1               3               0               1                2.000                1.000            0.667            0.333               2
14           2         4                  2                  2                    0               4               0               2                2.000                2.000            0.500            0.500               2
15           2         5                  2                  3                   -1               5               0               3                2.000                3.000            0.400            0.600               2
16           2         6                  3                  3                    0               6               1               0                2.000                3.000            0.500            0.500               2
17           2         7                  3                  4                   -1               7               0               1                1.000                4.000            0.429            0.571               2
18           2         8                  4                  4                    0               8               1               0                2.000                3.000            0.500            0.500               2
19           2         9                  5                  4                    1               9               2               0                3.000                2.000            0.556            0.444               2

### Agrupación por punto

In [60]:
# ============================================================
# AGREGACIÓN DE data_videos A NIVEL DE PUNTO
# ============================================================

# Normalizar team a mayúsculas
data_videos['team'] = data_videos['team'].str.upper()

data_videos_agg = data_videos.groupby(['partido', 'punto']).agg(

    # --- Duración del punto ---
    duracion_punto                  = ('video_duration', 'first'),

    # --- Velocidad de jugadores por equipo ---
    velocidad_prom_e1               = ('player_speed_mps', lambda x: x[data_videos.loc[x.index, 'team'] == 'BOTTOM'].mean()),
    velocidad_prom_e2               = ('player_speed_mps', lambda x: x[data_videos.loc[x.index, 'team'] == 'TOP'].mean()),
    velocidad_max_e1                = ('player_speed_mps', lambda x: x[data_videos.loc[x.index, 'team'] == 'BOTTOM'].max()),
    velocidad_max_e2                = ('player_speed_mps', lambda x: x[data_videos.loc[x.index, 'team'] == 'TOP'].max()),

    # --- Desplazamiento total por equipo ---
    desplazamiento_total_e1         = ('player_displacement', lambda x: x[data_videos.loc[x.index, 'team'] == 'BOTTOM'].sum()),
    desplazamiento_total_e2         = ('player_displacement', lambda x: x[data_videos.loc[x.index, 'team'] == 'TOP'].sum()),

    # --- Distancia promedio a la red por equipo ---
    dist_red_prom_e1                = ('distance_player_to_net_m', lambda x: x[data_videos.loc[x.index, 'team'] == 'BOTTOM'].mean()),
    dist_red_prom_e2                = ('distance_player_to_net_m', lambda x: x[data_videos.loc[x.index, 'team'] == 'TOP'].mean()),

    # --- Distancia promedio al compañero por equipo ---
    dist_companero_prom_e1          = ('distance_player_to_teammate_m', lambda x: x[data_videos.loc[x.index, 'team'] == 'BOTTOM'].mean()),
    dist_companero_prom_e2          = ('distance_player_to_teammate_m', lambda x: x[data_videos.loc[x.index, 'team'] == 'TOP'].mean()),

    # --- Golpes por equipo ---
    hits_e1                         = ('player_hits_ball', lambda x: x[data_videos.loc[x.index, 'team'] == 'BOTTOM'].sum()),
    hits_e2                         = ('player_hits_ball', lambda x: x[data_videos.loc[x.index, 'team'] == 'TOP'].sum()),

    # --- Velocidad de la pelota ---
    velocidad_prom_pelota           = ('ball_speed_mps', 'mean'),
    velocidad_max_pelota            = ('ball_speed_mps', 'max'),

    # --- Aceleración promedio por equipo ---
    aceleracion_prom_e1             = ('player_acceleration_mps2', lambda x: x[data_videos.loc[x.index, 'team'] == 'BOTTOM'].mean()),
    aceleracion_prom_e2             = ('player_acceleration_mps2', lambda x: x[data_videos.loc[x.index, 'team'] == 'TOP'].mean()),

).reset_index()

print(data_videos_agg.shape)
print(data_videos_agg.head(10).to_string())

(287, 19)
   partido  punto  duracion_punto  velocidad_prom_e1  velocidad_prom_e2  velocidad_max_e1  velocidad_max_e2  desplazamiento_total_e1  desplazamiento_total_e2  dist_red_prom_e1  dist_red_prom_e2  dist_companero_prom_e1  dist_companero_prom_e2  hits_e1  hits_e2  velocidad_prom_pelota  velocidad_max_pelota  aceleracion_prom_e1  aceleracion_prom_e2
0        1      1           5.267              0.449              0.305             3.394             1.697                    2.319                    3.168             7.085             5.531                   3.880                   4.203        3        0                  1.313                50.000                0.000                0.032
1        1      2           9.500              0.444              0.869             7.000             7.000                    3.810                   70.211             6.840             4.876                   4.198                   4.196        3        7                  1.611                50.000                0.000                0.083
2        1      3           4.600              0.138              0.206             1.697             1.697                    0.622                    1.867             7.058             5.432                   3.177                   3.380        2        2                  1.174                50.000               -0.074                0.037
3        1      4           5.600              0.175              0.150             1.697             7.000                    0.962                    5.188             7.792             5.498                   2.940                   4.036        0        3                  1.207                50.000                0.000                0.030
4        1      5           4.667              0.310              0.371             1.697             7.000                    1.414                    5.883             5.866             5.565                   2.580                   3.598        0        0                  0.397                50.000                0.073                0.072
5        1      6           7.133              0.921              0.383             6.788             7.000                    5.770                    6.675             7.347             4.952                   3.802                   4.536        0        0                  0.605                50.000               -0.053               -0.024
6        1      7           9.633              0.564              0.666             7.000             7.000                    4.186                   39.742             6.650             5.046                   3.581                   4.415        0        4                  1.858                50.000                0.045                0.017
7        1      8           9.367              0.402              0.350             3.394             7.000                    3.507                    9.504             7.533             5.593                   4.079                   4.534        3        7                  0.836                48.433                0.038                0.036
8        1      9           9.767              0.646              0.876             5.091             7.000                    5.148                   63.452             5.913             5.723                   3.024                   5.009        3        2                  1.587                50.000               -0.084                0.083
9        1     10           4.967              0.571              0.346             7.000             1.697                    4.546                    3.394             6.952             4.810                   4.261                   3.629        2        2                  1.967                50.000                0.137                0.034

### Join

In [62]:
# ============================================================
# JOIN: data_videos_agg + data_partidos
# ============================================================

data = data_videos_agg.merge(
    data_partidos,
    left_on=['partido', 'punto'],
    right_on=['ID_PARTIDO', 'ID_PUNTO'],
    how='inner'
)

# Eliminar columnas redundantes
data = data.drop(columns=['ID_PARTIDO', 'ID_PUNTO'])

print(f"Shape data_videos_agg: {data_videos_agg.shape}")
print(f"Shape data_partidos:   {data_partidos.shape}")
print(f"Shape data (join):     {data.shape}")
print(f"\nColumnas:\n{data.columns.tolist()}")
print(f"\nPrimeras filas:")
print(data.head())

Shape data_videos_agg: (287, 19)
Shape data_partidos:   (406, 26)
Shape data (join):     (283, 43)

Columnas:
['partido', 'punto', 'duracion_punto', 'velocidad_prom_e1', 'velocidad_prom_e2', 'velocidad_max_e1', 'velocidad_max_e2', 'desplazamiento_total_e1', 'desplazamiento_total_e2', 'dist_red_prom_e1', 'dist_red_prom_e2', 'dist_companero_prom_e1', 'dist_companero_prom_e2', 'hits_e1', 'hits_e2', 'velocidad_prom_pelota', 'velocidad_max_pelota', 'aceleracion_prom_e1', 'aceleracion_prom_e2', 'CANCHA', 'ID_JUGADOR_1_EQUIPO_1', 'ID_JUGADOR_2_EQUIPO_1', 'ID_JUGADOR_1_EQUIPO_2', 'ID_JUGADOR_2_EQUIPO_2', 'EQUIPO_1_POSICION', 'EQUIPO_2_POSICION', 'POSICION_JUGADOR_1_EQUIPO_1', 'POSICION_JUGADOR_2_EQUIPO_1', 'POSICION_JUGADOR_1_EQUIPO_2', 'POSICION_JUGADOR_2_EQUIPO_2', 'PUNTO_EQUIPO_1', 'PUNTO_EQUIPO_2', 'MARCADOR_EQUIPO_1', 'MARCADOR_EQUIPO_2', 'EQUIPO_GANADOR', 'DIFERENCIA_MARCADOR', 'PUNTOS_JUGADOS', 'WINRATE_ACUM_E1', 'WINRATE_ACUM_E2', 'RACHA_EQUIPO_1', 'RACHA_EQUIPO_2', 'PUNTOS_ULTIMOS_5_E1', 'PUNTOS_ULTIMOS_5_E2']

Primeras filas:
   partido  punto  duracion_punto  velocidad_prom_e1  velocidad_prom_e2  \
0        1      1           5.267              0.449              0.305
1        1      2           9.500              0.444              0.869
2        1      3           4.600              0.138              0.206
3        1      4           5.600              0.175              0.150
4        1      5           4.667              0.310              0.371

   velocidad_max_e1  velocidad_max_e2  desplazamiento_total_e1  \
0             3.394             1.697                    2.319
1             7.000             7.000                    3.810
2             1.697             1.697                    0.622
3             1.697             7.000                    0.962
4             1.697             7.000                    1.414

   desplazamiento_total_e2  dist_red_prom_e1  dist_red_prom_e2  \
0                    3.168             7.085             5.531
1                   70.211             6.840             4.876
2                    1.867             7.058             5.432
3                    5.188             7.792             5.498
4                    5.883             5.866             5.565

   dist_companero_prom_e1  dist_companero_prom_e2  hits_e1  hits_e2  \
0                   3.880                   4.203        3        0
1                   4.198                   4.196        3        7
2                   3.177                   3.380        2        2
3                   2.940                   4.036        0        3
4                   2.580                   3.598        0        0

   velocidad_prom_pelota  velocidad_max_pelota  aceleracion_prom_e1  \
0                  1.313                50.000                0.000
1                  1.611                50.000                0.000
2                  1.174                50.000               -0.074
3                  1.207                50.000                0.000
4                  0.397                50.000                0.073

   aceleracion_prom_e2  CANCHA      ID_JUGADOR_1_EQUIPO_1  \
0                0.032       1  Alejandra Salazar Galeano
1                0.083       1  Alejandra Salazar Galeano
2                0.037       1  Alejandra Salazar Galeano
3                0.030       1  Alejandra Salazar Galeano
4                0.072       1  Alejandra Salazar Galeano

          ID_JUGADOR_2_EQUIPO_1  ID_JUGADOR_1_EQUIPO_2  \
0  Angel Santiago Toribio Godoy  Santiago Pena Beltran
1  Angel Santiago Toribio Godoy  Santiago Pena Beltran
2  Angel Santiago Toribio Godoy  Santiago Pena Beltran
3  Angel Santiago Toribio Godoy  Santiago Pena Beltran
4  Angel Santiago Toribio Godoy  Santiago Pena Beltran

           ID_JUGADOR_2_EQUIPO_2 EQUIPO_1_POSICION EQUIPO_2_POSICION  \
0  Sahily Andrea Herrera Eljadue            BOTTOM               TOP
1  Sahily Andrea Herrera Eljadue            BOTTOM               TOP
2  Sahily Andrea Herrera Eljadue            BOTTOM               TOP
3  Sahily Andrea Herrera Eljadue            BOTTOM               TOP
4  Sahily Andrea Herrera Eljadue            BOTTOM               TOP

  POSICION_JUGADOR_1_EQUIPO_1 POSICION_JUGADOR_2_EQUIPO_1  \
0                       RIGHT                        LEFT
1                       RIGHT                        LEFT
2                       RIGHT                        LEFT
3                       RIGHT                        LEFT
4                       RIGHT                        LEFT

  POSICION_JUGADOR_1_EQUIPO_2 POSICION_JUGADOR_2_EQUIPO_2  PUNTO_EQUIPO_1  \
0                       RIGHT                        LEFT               1
1                       RIGHT                        LEFT               1
2                       RIGHT                        LEFT               0
3                       RIGHT                        LEFT               0
4                       RIGHT                        LEFT               0

   PUNTO_EQUIPO_2  MARCADOR_EQUIPO_1  MARCADOR_EQUIPO_2  EQUIPO_GANADOR  \
0               0                  1                  0               1
1               0                  2                  0               1
2               1                  2                  1               1
3               1                  2                  2               1
4               1                  2                  3               1

   DIFERENCIA_MARCADOR  PUNTOS_JUGADOS  WINRATE_ACUM_E1  WINRATE_ACUM_E2  \
0                    1               1            1.000            0.000
1                    2               2            1.000            0.000
2                    1               3            0.667            0.333
3                    0               4            0.500            0.500
4                   -1               5            0.400            0.600

   RACHA_EQUIPO_1  RACHA_EQUIPO_2  PUNTOS_ULTIMOS_5_E1  PUNTOS_ULTIMOS_5_E2
0               1               0                1.000                0.000
1               2               0                2.000                0.000
2               0               1                2.000                1.000
3               0               2                2.000                2.000
4               0               3                2.000                3.000

In [63]:
data.head(10)

,partido,punto,duracion_punto,velocidad_prom_e1,velocidad_prom_e2,velocidad_max_e1,velocidad_max_e2,desplazamiento_total_e1,desplazamiento_total_e2,dist_red_prom_e1,dist_red_prom_e2,dist_companero_prom_e1,dist_companero_prom_e2,hits_e1,hits_e2,velocidad_prom_pelota,velocidad_max_pelota,aceleracion_prom_e1,aceleracion_prom_e2,CANCHA,ID_JUGADOR_1_EQUIPO_1,ID_JUGADOR_2_EQUIPO_1,ID_JUGADOR_1_EQUIPO_2,ID_JUGADOR_2_EQUIPO_2,EQUIPO_1_POSICION,EQUIPO_2_POSICION,POSICION_JUGADOR_1_EQUIPO_1,POSICION_JUGADOR_2_EQUIPO_1,POSICION_JUGADOR_1_EQUIPO_2,POSICION_JUGADOR_2_EQUIPO_2,PUNTO_EQUIPO_1,PUNTO_EQUIPO_2,MARCADOR_EQUIPO_1,MARCADOR_EQUIPO_2,EQUIPO_GANADOR,DIFERENCIA_MARCADOR,PUNTOS_JUGADOS,WINRATE_ACUM_E1,WINRATE_ACUM_E2,RACHA_EQUIPO_1,RACHA_EQUIPO_2,PUNTOS_ULTIMOS_5_E1,PUNTOS_ULTIMOS_5_E2
0,1,1,5.267,0.449,0.305,3.394,1.697,2.319,3.168,7.085,5.531,3.880,4.203,3,0,1.313,50.000,0.000,0.032,1,Alejandra Salazar Galeano,Angel Santiago Toribio Godoy,Santiago Pena Beltran,Sahily Andrea Herrera Eljadue,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,1,0,1,0,1,1,1,1.000,0.000,1,0,1.000,0.000
1,1,2,9.500,0.444,0.869,7.000,7.000,3.810,70.211,6.840,4.876,4.198,4.196,3,7,1.611,50.000,0.000,0.083,1,Alejandra Salazar Galeano,Angel Santiago Toribio Godoy,Santiago Pena Beltran,Sahily Andrea Herrera Eljadue,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,1,0,2,0,1,2,2,1.000,0.000,2,0,2.000,0.000
2,1,3,4.600,0.138,0.206,1.697,1.697,0.622,1.867,7.058,5.432,3.177,3.380,2,2,1.174,50.000,-0.074,0.037,1,Alejandra Salazar Galeano,Angel Santiago Toribio Godoy,Santiago Pena Beltran,Sahily Andrea Herrera Eljadue,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,0,1,2,1,1,1,3,0.667,0.333,0,1,2.000,1.000
3,1,4,5.600,0.175,0.150,1.697,7.000,0.962,5.188,7.792,5.498,2.940,4.036,0,3,1.207,50.000,0.000,0.030,1,Alejandra Salazar Galeano,Angel Santiago Toribio Godoy,Santiago Pena Beltran,Sahily Andrea Herrera Eljadue,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,0,1,2,2,1,0,4,0.500,0.500,0,2,2.000,2.000
4,1,5,4.667,0.310,0.371,1.697,7.000,1.414,5.883,5.866,5.565,2.580,3.598,0,0,0.397,50.000,0.073,0.072,1,Alejandra Salazar Galeano,Angel Santiago Toribio Godoy,Santiago Pena Beltran,Sahily Andrea Herrera Eljadue,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,0,1,2,3,1,-1,5,0.400,0.600,0,3,2.000,3.000
5,1,6,7.133,0.921,0.383,6.788,7.000,5.770,6.675,7.347,4.952,3.802,4.536,0,0,0.605,50.000,-0.053,-0.024,1,Alejandra Salazar Galeano,Angel Santiago Toribio Godoy,Santiago Pena Beltran,Sahily Andrea Herrera Eljadue,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,1,0,3,3,1,0,6,0.500,0.500,1,0,2.000,3.000
6,1,7,9.633,0.564,0.666,7.000,7.000,4.186,39.742,6.650,5.046,3.581,4.415,0,4,1.858,50.000,0.045,0.017,1,Alejandra Salazar Galeano,Angel Santiago Toribio Godoy,Santiago Pena Beltran,Sahily Andrea Herrera Eljadue,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,1,0,4,3,1,1,7,0.571,0.429,2,0,2.000,3.000
7,1,8,9.367,0.402,0.350,3.394,7.000,3.507,9.504,7.533,5.593,4.079,4.534,3,7,0.836,48.433,0.038,0.036,1,Alejandra Salazar Galeano,Angel Santiago Toribio Godoy,Santiago Pena Beltran,Sahily Andrea Herrera Eljadue,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,1,0,5,3,1,2,8,0.625,0.375,3,0,3.000,2.000
8,1,9,9.767,0.646,0.876,5.091,7.000,5.148,63.452,5.913,5.723,3.024,5.009,3,2,1.587,50.000,-0.084,0.083,1,Alejandra Salazar Galeano,Angel Santiago Toribio Godoy,Santiago Pena Beltran,Sahily Andrea Herrera Eljadue,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,1,0,6,3,1,3,9,0.667,0.333,4,0,4.000,1.000
9,1,10,4.967,0.571,0.346,7.000,1.697,4.546,3.394,6.952,4.810,4.261,3.629,2,2,1.967,50.000,0.137,0.034,1,Alejandra Salazar Galeano,Angel Santiago Toribio Godoy,Santiago Pena Beltran,Sahily Andrea Herrera Eljadue,BOTTOM,TOP,RIGHT,LEFT,RIGHT,LEFT,0,1,6,4,1,2,10,0.600,0.400,0,1,4.000,1.000